package Lib;

public enum Waifus {
	Elza("Elza","https://exviuswiki.com//images/0/08/Unit-Elza-6.png"),
	Tilith("Tilith","https://exviuswiki.com//images/f/f3/Unit-Tilith-5.png"),
	Rosa("Rosa","https://exviuswiki.com//images/b/b9/Unit-Rosa-5.png"),
	Xiao("Xiao","https://exviuswiki.com//images/4/41/Unit-Xiao-5.png"),
	Lenna("Lenna","https://exviuswiki.com//images/b/ba/Unit-Lenna-5.png"),
	Garnet("Garnet","https://exviuswiki.com//images/f/f3/Unit-Garnet-5.png"),
	Celes("Celes","https://exviuswiki.com//images/0/08/Unit-Celes-5.png"),
	Seria("Seria","https://exviuswiki.com//images/2/2a/Unit-Seria-5.png"),
	Chizuru("Chizuru","https://exviuswiki.com//images/4/45/Unit-Chizuru-5.png"),
	Fina("Fina","https://exviuswiki.com//images/5/5a/Unit-Fina-5.png"),
	VLCFina("White Witch Fina","https://exviuswiki.com//images/0/07/Unit-White_Witch_Fina-6.png"),
	MajinFina("Majin Fina","https://exviuswiki.com/images/9/92/Unit-Dark_Fina-6.png"),
	SumFina("Beach Time Fina","https://exviuswiki.com/images/4/46/Unit-Beach_Time_Fina-6.png"),
	SumMajinFina("Sea Breeze Dark Fina","https://exviuswiki.com/images/2/28/Unit-Seabreeze_Dark_Fina-6.png"),
	Lid("Lid","https://exviuswiki.com//images/4/49/Unit-Lid-5.png"),
	SumLid("Summer Lid","https://exviuswiki.com//images/e/e5/Unit-Summer_Lid-5.png"),
	BCLid("Black Cat Lid","https://exviuswiki.com//images/1/1c/Unit-Black_Cat_Lid-5.png"),
	Leah("Leah","https://exviuswiki.com//images/d/de/Unit-Leah-2.png"),
	Liza("Liza","https://exviuswiki.com//images/8/84/Unit-Liza-2.png"),
	Sarah("Sarah","https://exviuswiki.com//images/e/e1/Unit-Sarah-3.png"),
	Mel("Mel","https://exviuswiki.com//images/6/68/Unit-Mel-3.png"),
	Sarai("Sarai","https://exviuswiki.com//images/1/10/Unit-Sarai-2.png"),
	Paula("Paula","https://exviuswiki.com//images/f/f9/Unit-Paula-3.png"),
	Carrie("Carrie","https://exviuswiki.com/images/d/d3/Unit-Carrie-3.png"),
	Skaha("Skaha","https://exviuswiki.com/images/3/32/Unit-Skaha-3.png"),
	Penelo("Penelo","https://exviuswiki.com/images/5/5a/Unit-Penelo-4.png"),
	Maria("Maria","https://exviuswiki.com/images/2/28/Unit-Maria-4.png"),
	Krile("Krile","https://exviuswiki.com/images/a/a9/Unit-Krile-4.png"),
	Fran("Fran","https://exviuswiki.com/images/1/1e/Unit-Fran-4.png"),
	Rydia("Rydia","https://exviuswiki.com/images/1/15/Unit-Rydia-5.png"),
	Luna("Luna","https://exviuswiki.com/images/d/d4/Unit-Luna-4.png"),
	CoD("Cloud of Darkness","https://exviuswiki.com/images/7/7c/Unit-Cloud_of_Darkness-6.png"),
	Terra("Terra","https://exviuswiki.com/images/e/ec/Unit-Terra-5.png"),
	Cerius("Cerius","https://exviuswiki.com/images/5/58/Unit-Cerius-5.png"),
	Roselia("Roselia","https://exviuswiki.com/images/c/cf/Unit-Roselia-5.png"),
	Miyuki("Miyuki","https://exviuswiki.com/images/e/ed/Unit-Miyuki-5.png"),
	Rakshasa("Rakshasa","https://exviuswiki.com/images/0/0b/Unit-Rakshasa-5.png"),
	Lani("Lani","https://exviuswiki.com/images/b/ba/Unit-Lani-4.png"),
	Freya("Freya","https://exviuswiki.com/images/f/fc/Unit-Freya-5.png"),
	Charlotte("Charlotte","https://exviuswiki.com/images/c/c5/Unit-Charlotte-5.png"),
	Ludmille("Ludmille","https://exviuswiki.com/images/0/04/Unit-Ludmille-5.png"),
	Lightning("Lightning","https://exviuswiki.com/images/2/25/Unit-Lightning-6.png"),
	Alma("Alma","https://exviuswiki.com/images/3/3f/Unit-Alma-5.png"),
	Arigas("Arigas","https://exviuswiki.com/images/b/b5/Unit-Agrias-5.png"),
	Refia("Refia","https://exviuswiki.com/images/a/ae/Unit-Refia-6.png"),
	ArmTerra("Majitek Armour Terra","https://exviuswiki.com/images/d/df/Unit-Magitek_Armor_Terra-4.png"),
	Fencer("Fencer","https://exviuswiki.com/images/0/02/Unit-Fencer-5.png"),
	TM("Trust Moogle :stuck_out_tongue:","https://exviuswiki.com/images/f/f5/Unit-Trust_Moogle-5.png"),
	Nicol("Nicol","https://exviuswiki.com/images/5/59/Unit-Nichol-5.png"),
	Sakura("Sakura","https://exviuswiki.com/images/3/3f/Unit-Sakura-5.png"),
	Vanille("Vanille","https://exviuswiki.com/images/5/5d/Unit-Vanille-5.png"),
	Fang("Fang","https://exviuswiki.com/images/9/9c/Unit-Fang-5.png"),
	Seven("Seven","https://exviuswiki.com/images/7/72/Unit-Seven-6.png"),
	Faris("Faris","https://exviuswiki.com/images/2/25/Unit-Faris-5.png"),
	Mercedes("Mercedes","https://exviuswiki.com/images/b/b6/Unit-Mercedes-6.png"),
	Clinque("Clinque","https://exviuswiki.com/images/e/e9/Unit-Cinque-5.png"),
	Queen("Queen","https://exviuswiki.com/images/7/76/Unit-Queen-6.png"),
	Luka("Luka","https://exviuswiki.com/images/7/75/Unit-Luka-6.png"),
	Ovelia("Ovelia","https://exviuswiki.com/images/b/b9/Unit-Ovelia-5.png"),
	Soleil("Soleil","https://exviuswiki.com/images/3/33/Unit-Soleil-6.png"),
	Shine("Shine","https://exviuswiki.com/images/3/30/Unit-Shine-6.png"),
	Marie("Marie","https://exviuswiki.com/images/7/79/Unit-Marie-6.png"),
	Ulrica("Ulrikca","https://exviuswiki.com/images/1/14/Unit-Ulrica-5.png"),
	Eileen("Aileen","https://exviuswiki.com/images/4/49/Unit-Aileen-6.png"),
	Rem("Rem","https://exviuswiki.com/images/b/b6/Unit-Rem-6.png"),
	Jean("Jean","https://exviuswiki.com/images/9/91/Unit-Jean-5.png"),
	Grace("Grace","https://exviuswiki.com/images/8/8c/Unit-Grace-6.png"),
	TranceTerra("Trance Terra","https://exviuswiki.com/images/c/c9/Unit-Trance_Terra-6.png"),
	Amelia("Amelia","https://exviuswiki.com/images/9/9e/Unit-Amelia-6.png"),
	Camille("Camille","https://exviuswiki.com/images/e/e4/Unit-Camille-5.png"),
	Rikku("Rikku","https://exviuswiki.com/images/e/ee/Unit-Rikku-6.png"),
	Ashe("Ashe","https://exviuswiki.com/images/c/c4/Unit-Ashe-6.png"),
	Lunera("Lunera","https://exviuswiki.com/images/f/f5/Unit-Lunera-6.png"),
	Helena("Helena","https://exviuswiki.com/images/5/51/Unit-Helena-6.png"),
	Prishe("Prishe","https://exviuswiki.com/images/a/a2/Unit-Prishe-6.png"),
	Meliadoul("Meliadoul","https://exviuswiki.com/images/d/df/Unit-Meliadoul-6.png"),
	Victoria("Victoria","https://exviuswiki.com/images/8/85/Unit-Victoria-6.png"),
	Aria("Aria","https://exviuswiki.com/images/4/4b/Unit-Aria-6.png"),
	Sara("Sara","https://exviuswiki.com/images/8/85/Unit-Sara-5.png"),
	Aura("Aura","https://exviuswiki.com/images/2/25/Unit-Aura-6.png"),
	Samantha("Samantha","https://exviuswiki.com/images/9/9a/Unit-Samatha-4.png"),
	Popoi("Popoi","https://exviuswiki.com/images/8/80/Unit-Popoi-5.png"),
	Primm("Primm","https://exviuswiki.com/images/d/d9/Unit-Primm-6.png"),
	Maxell("Creator Maxell","https://exviuswiki.com/images/7/7f/Unit-Maxwell-6.png"),
	Minfila("Minfila","https://exviuswiki.com/images/6/60/Unit-Minfilia-6.png"),
	YShtola("Y'shtola","https://exviuswiki.com/images/2/27/Unit-Y%27shtola-6.png"),
	Mog("Mog:confused: ","https://exviuswiki.com/images/d/d9/Unit-Mog-6.png"),
	Shantotto("Shantotto","https://exviuswiki.com/images/4/43/Unit-Shantotto-5.png"),
	Crowe("Crowe","https://exviuswiki.com/images/4/44/Unit-Crowe-6.png"),
	Lorraine("Lorraine","https://exviuswiki.com/images/5/59/Unit-Lorraine-6.png"),
	Ayaka("Ayaka","https://exviuswiki.com/images/f/f1/Unit-Ayaka-6.png"),
	Sylvia("Sylvia","https://exviuswiki.com/images/f/f6/Unit-Sylvia-6.png"),
	Yuri("Yuri","https://exviuswiki.com/images/4/4e/Unit-Yuri-5.png"),
	HuntFina("Hunter Fina","https://exviuswiki.com/images/7/75/Unit-Hunter_Fina-6.png"),
	HuntLid("Hunter Lid","https://exviuswiki.com/images/3/37/Unit-Hunter_Lid-5.png"),
	HuntSakura("Hunter Sakura","https://exviuswiki.com/images/d/da/Unit-Hunter_Sakura-6.png");
	
	public String name;
	public String url;
	Waifus(String name, String url){
		this.name=name;
		this.url=url;
	}
}
